# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvefile',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curvefile',
            name='filename',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
